/// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1HcbukRU1cXeUOWGX8Zy6eohr-Zf6DCA',
    appId: '1:329679272766:web:56148973422cfd1d8bca6f',
    messagingSenderId: '329679272766',
    projectId: 'kt-8-e565b',
    authDomain: 'kt-8-e565b.firebaseapp.com',
    storageBucket: 'kt-8-e565b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQrRq9qnwodYnN6BKXcOL5k1qkAHvKdac',
    appId: '1:329679272766:android:ff78354c7ae499708bca6f',
    messagingSenderId: '329679272766',
    projectId: 'kt-8-e565b',
    storageBucket: 'kt-8-e565b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv0N3O5JLGC13e2wslqNTbzBQqzkjnwx8',
    appId: '1:329679272766:ios:03ac0847896935c08bca6f',
    messagingSenderId: '329679272766',
    projectId: 'kt-8-e565b',
    storageBucket: 'kt-8-e565b.appspot.com',
    iosClientId: '329679272766-ofotd0d5ka2ti8upvp27o841fpnku8np.apps.googleusercontent.com',
    iosBundleId: 'com.example.kt8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv0N3O5JLGC13e2wslqNTbzBQqzkjnwx8',
    appId: '1:329679272766:ios:6cb103a5e8635ae08bca6f',
    messagingSenderId: '329679272766',
    projectId: 'kt-8-e565b',
    storageBucket: 'kt-8-e565b.appspot.com',
    iosClientId: '329679272766-f9ptpq8630nrlfp3eu2ekoovggnecs9i.apps.googleusercontent.com',
    iosBundleId: 'com.example.kt8.RunnerTests',
  );
}
